---
title: "dynamic regression"
author: "Anh Tran"
date: "2022-12-25"
output: github_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

library(fpp3)
```

## Load & prepare data
```{r}
data <- read.csv("data.csv")
data$date <- as.Date(data$date)
data <- data %>% as_tsibble(key = item_id, index = date)

data_train <- read.csv("data_train_merged.csv")
data_train$date <- as.Date(data_train$date)
data_train <- data_train %>% as_tsibble(key = item_id, index = date)

data_test <- read.csv("data_test_merged.csv")
data_test$date <- as.Date(data_test$date)
data_test <- data_test %>% as_tsibble(key = item_id, index = date)

data_train$events <- ifelse(is.na(data_train$event_name_1), 0, 1)
data_test$events <- ifelse(is.na(data_test$event_name_1), 0, 1)
```

## Dynamic regression

```{r}
fit_dynamic_reg <- data_train %>% model(ARIMA(sales ~ events))
```

```{r}
fc_dynamic_reg <- fit_dynamic_reg %>% forecast(new_data = data_test)
sample_n(fc_dynamic_reg, 3) %>% autoplot(data)
```

### Accuracy
```{r}
rmse_dynamic_reg <- mean(accuracy(fc_dynamic_reg, data)$RMSE)
rmse_dynamic_reg
```

